osx_image: xcode8
language: objective-c
script:
- set -o pipefail && xcodebuild test -workspace Example/FlexiblePageViewController.xcworkspace -scheme FlexiblePageViewController-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
